using Feast.JsonAnnotation.Extensions;
using Microsoft.CodeAnalysis;
using System;
using System.Diagnostics;

namespace Feast.JsonAnnotation.Generators
{
    [Generator]
    internal class JsonAnnotationGenerator : ISourceGenerator
    {
        private readonly JsonAnnotationReceiver receiver = new();
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => receiver);
        }

        public void Execute(GeneratorExecutionContext context)
        {
            if (receiver.Generated) return;
            receiver.Generated = true;
            var s = $"// <auto-generated/>\nusing System;\n\n" +
                    receiver.ClassUsing.TypeUsing.FormatNamespaceStrings();
            // Add the source code to the compilation
            context.AddSource($"{Guid.NewGuid().ToString().Replace('-', '_')}.g.cs", s);
        }
    }
}
