using System.IO;
using Feast.JsonAnnotation.Extensions;
using Microsoft.CodeAnalysis;

namespace Feast.JsonAnnotation.Generators
{
    [Generator]
    internal class JsonAnnotationGenerator : ISourceGenerator
    {
        private readonly JsonAnnotationReceiver receiver = new();
        public void Initialize(GeneratorInitializationContext context)
        {
            context.RegisterForSyntaxNotifications(() => receiver);
        }

        public void Execute(GeneratorExecutionContext context)
        {
            var s = $"// <auto-generated/>\nusing System;\n\n" +
                    receiver.ClassUsing.TypeUsing.FormatNamespaceStrings();

            // Add the source code to the compilation
            context.AddSource($"Model.g.cs", s);
        }
    }
}
